# Dependencies
markdown:         kramdown
highlighter:      rouge

# Permalinks
permalink:        pretty

# Setup
title:            Cal 2
tagline:          'Notes, problems, and videos'
description:      'Notes, problems, and videos for your Calculus 2 course.'
url:              https://stevenclontz.github.io/teaching-2016-08-17-fall/
baseurl:          /teaching-2016-08-17-fall/

author:
  name:           'Steven Clontz'
  url:            http://clontz.org

gems:
  - jekyll-paginate
paginate:         5

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/StevenClontz/teaching-2016-08-17-fall
